name: Build
description: Sets up ruby and node. Installs node dependencies.
author: Roberto Welzel Filho <rwelzel@epages.com>

inputs:
  ruby_version:
    description: The ruby version to be used. Defaults to 2.7.5
    required: true
    default: 2.7.5
  node_version:
    description: The node version to be used. Defaults to 16
    required: true
    default: '16'

runs:
  using: composite
  steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ inputs.ruby_version }}
        bundler-cache: true
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ inputs.node_version }}
        cache: yarn
    - shell: bash
      run: yarn install --production=false